version: "3"

volumes:
  staticfiles:

services:

  db:
    container_name: database
    image: postgres:alpine
    volumes:
      - ./db:/var/lib/postgresql/data
      - ./init.sh:/docker-entrypoint-initb.d/init.sh
    environment:
      - POSTGRES_DB=paymentsdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: on-failure:3

  redis:
    container_name: redis
    image: redis
    command: redis-server
    ports:
      - '6379:6379'
    restart: on-failure:3

  web:
    container_name: web
    build: .
    command: gunicorn --workers=3 paymentAPI.wsgi -b 0.0.0.0:8000
    volumes:
      - .:/code
      - ./staticfiles:/code/static
    env_file:
      - ./.env
    entrypoint:
      - ./entrypoint.sh
    expose:
      - "8000"
    depends_on:
      - db
      - redis
    restart: on-failure:3

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./staticfiles:/static
    depends_on:
      - web
    restart: on-failure:3

  celery:
    container_name: celery
    build: .
    command: /home/eblackbu/.local/bin/celery -A paymentAPI worker -l INFO -B
    volumes:
      - .:/code
    links:
      - redis
    env_file:
      - ./.env
    depends_on:
      - web
    restart: on-failure:3
