# Generated by Django 3.2.5 on 2021-07-10 08:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentAccount',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('initials', models.CharField(max_length=200, verbose_name='ФИО')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Баланс')),
                ('hold', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Холд')),
                ('status', models.BooleanField(default=True, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Счет абонента',
                'verbose_name_plural': 'Счета абонентов',
            },
        ),
    ]
